package pkginfodb

var GROUPS = map[string]([]string){
	"cross": CROSS, // this should allways be built first!
	"core0": CORE0, // fundamental technical core
	"core1": CORE1, // operating system sufficient for user

	// NOTE: let's concentrate on 3 abowe first.
	// "crypt": CRYPT,
	// "fd": FD,
	//
	// "fi":  FI,
	// "fib": FIB,
}

var CROSS = []string{
	"cloog", "isl", "gmp", "mpc", "mpfr", "glibc", "linux", "binutils", "gcc",
}

var CORE0 = []string{
	"go",
	"tor",
	"patchelf",
	"flex",
	"make",
	"talloc",
	"intltool",
	"inetutils",
	"acl",
	"attr",
	"autoconf",
	"autogen",
	"automake",
	"bash",
	"bzip2",
	"check",
	"cmake",
	"coreutils",
	"dbus",
	"dbus-glib",
	"dbus-python",
	"db",
	"dejagnu",
	"diffutils",
	"emacs",
	"expect",
	"findutils",
	"gawk",
	"gdb",
	"gettext",
	"glib",
	"git",
	"git-manpages",
	"gperf",
	"grep",
	"guile",
	"gzip",
	"icu4c",
	"iproute2",
	"iptables",
	"kbd",
	"kmod",
	"libcap2",
	"libcap-ng",
	"libffi",
	"libidn",
	"libtool",
	"libunistring",
	"m4",
	"mc",
	"nano",
	"ncurses",
	"nftables",
	"openssh",
	"openssl",
	"fuse",
	"patch",
	"pcre",
	"pcre2",
	"pkg-config",
	"polkit",
	"Python2",
	"Python3",
	"readline",
	"sed",
	"shadow",
	"slang",
	"sshfs-fuse",
	"systemd",
	"syslinux",
	"grub2",
	"sqlite-autoconf",
	"tar",
	"tzdata",
	"nasm",
	"tcl",
	"tcpdump",
	"tdb",
	"texinfo",
	"tk",
	"unzip",
	"util-linux",
	"parted",
	"which",
	"xz",
	"yasm",
	"zip",
	"zlib",
	"itstool",
	"xfsdump",
	"xfsprogs",
	"expat",
	"gc",
	"libatomic_ops",
	"bison",
	"procps-ng",
	"psmisc",
	"less",
	"libmicrohttpd",
	"lzo",
	"gdbm",
	"wget",
	"perl",
}

var CORE1 = []string{
	"NetworkManager",
	"libsoup",
	"libsecret",
	"mdadm",
	"lvm2",
	"avahi",
	"cryptsetup",
	"bc",
	"lsof",
	"dosfstools",
	"apr",
	"apr-util",
	"cpio",
	"bridge-utils",
	"boost",
	"apache-ant",
	"dev86",
	"bind9",
	"bluez",
	"curl",
	"dhcp",
	"dhcpcd",
	"dovecot",
	"e2fsprogs",
	"squashfs",
	"exim",
	"cyrus-sasl",
	"gsasl",
	"elfutils",
	"file",
	"openjdk8",
	"ilmbase",
	"imagemagick",
	"libgcrypt",
	"libseccomp",
	"libtirpc",
	"libusb",
	"groff",
	"lynx",
	"libnftnl",
	"libmnl",
	"json-c",
	"Linux-PAM",
	"man",
	"man-db",
	"man-pages",
	"net-snmp",
	"libpipeline",
	"ntp",
	"openexr",
	"openvpn",
	"ppp",
	"pptpd",
	"rp-l2tp",
	"rp-pppoe",
	"scons",
	"sudo",
	"qrencode",
	"zint",
	"zbar",
	"cups",
	"ijs",
	"cups-filters",
	"foomatic-db-engine",
	"foomatic-filters",
	"qpdf",
	"wireless_tools",
	"wpa_supplicant",
	"kismet",
	"tree",
	"libpcap",
	"pciutils",
	"usbutils",
	"xmlto",
	"cppunit",
	"libgssapi",
	"gss",
	"gssdp",
	"libgssglue",
	"librpcsecgss",
	"libnfsidmap",
	"shishi",
	"doxygen",
	"p7zip",
	"mtdev",
	"xterm",
	"iso-codes",
	"libnl",
	"openldap",
	"libatasmart",
	"bash-completion",
	"ModemManager",
	"graphviz",
	"qemu",
	"neon",
	"tor",
	"torsocks",
	"libevent",
	"asciidoc",
	"libpwquality",
	"cracklib",
	"krb5",
	"subversion",
	"hamcrest-java",
	"rsync",
	"valgrind",
	"miniupnpd",
	"miniupnpc",
	"mono",
	"acpica-unix",
	"ntfs-3g_ntfsprogs",
	"libyaml",
	"npth",
	"libpthread-stubs",
	"hdparm",
	"smartmontools",
	"cabextract",
	"iw",
	"policycoreutils",
	"poco",
}

var CRYPT = []string{
	"gnupg1", "gnupg2", "gnutls", "gpa", "gpgme", "libassuan", "libgcrypt", "libgpg-error", "libksba",
	"libtasn1", "nettle", "nettle2", "npth", "scute", "p11-kit",

	"openssl",
}

var FD = []string{
	"xproto",
	"libXau",
	"libpthread-stubs",
	"libpciaccess",
	"colord",
	"colord-gtk",
	"desktop-file-utils",
	"libdrm",
	"fontconfig",
	"libevdev",
	"libgusb",
	"geoclue",
	"hicolor-icon-theme",
	"libepoxy",
	"libmbim",
	"libinput",
	"liboil",
	"pixman",
	"exempi",
	"libopenraw",
	"libqmi",
	"libspectre",
	"media-player-info",
	"libnice",
	"p11-kit",
	"pkg-config",
	"polkit",
	"plymouth",
	"poppler",
	"poppler-data",
	"pulseaudio",
	"shared-mime-info",
	"startup-notification",
	"icon-naming-utils",
	"tango-icon-theme",
	"udisks",
	"upower",
	"libxcb",
	"xcb-proto",
	"xcb-util",
	"xcb-util-cursor",
	"xcb-util-image",
	"xcb-util-keysyms",
	"xcb-util-renderutil",
	"xcb-util-wm",
	"farstream",
	"farsight",
	"farsight2",
	"libjingle",
	"telepathy-glib",
	"telepathy-inspector",
	"telepathy-mission-control",
	"telepathy-farstream",
	"telepathy-gabble",
	"telepathy-haze",
	"telepathy-idle",
	"telepathy-salut",
	"telepathy-logger",
}

var FI = []string{
	"pkg-config", "openssl", "gnupg1", "gnupg2", "gnutls", "gpa", "gpgme", "libassuan", "libgcrypt",
	"libgpg-error", "libksba", "libtasn1", "nettle", "nettle2", "npth", "scute", "p11-kit", "file", "less",
	"ncurses", "bash", "glibc", "coreutils", "linux", "readline", "util-linux", "parted", "squashfs",
	"sqlite-autoconf", "syslinux", "grub2", "mc", "slang", "glib", "nano", "Python3", "tar", "xz", "gzip",
	"bzip2", "zlib", "e2fsprogs", "dosfstools", "attr", "acl", "kmod", "iproute2", "iptables", "groff",
	"less", "findutils", "pcre", "pcre2", "grep", "sed", "gc", "libatomic_ops", "procps-ng", "psmisc", "gdbm", "db",
	"inetutils", "man", "texinfo", "pciutils", "usbutils", "libcap2", "mdadm", "lvm2", "cryptsetup", "gcc",
	"gmp", "mpfr", "mpc", "isl", "cloog",
}

var FIB = []string{
	"libcap2", "ncurses", "bash", "glibc", "coreutils", "readline", "util-linux", "xz", "zlib",
	"e2fsprogs", "attr", "acl",
}

var GL = []string{
	"mesa", "MesaGLUT", "glu", "glw", "glm", "mesa-demos", "glew", "freeglut", "vdpauinfo", "libvdpau",
	"libomxil-bellagio",
}

var GTK = []string{
	"libglade",
	"GConf",
	"at-spi2-atk",
	"at-spi2-core",
	"atk",
	"atkmm",
	"cairo",
	"cairomm",
	"dconf",
	"fontconfig",
	"freetype",
	"gdk-pixbuf",
	"glib",
	"glib-networking",
	"glibmm",
	"gmime",
	"gobject-introspection",
	"gtk+",
	"gtk+2",
	"gtk-doc",
	"gtk-engines",
	"gtkhtml",
	"gtkmm",
	"gtksourceview",
	"harfbuzz",
	"json-glib",
	"librsvg",
	"libsigc++",
	"pango",
	"pangomm",
	"py2cairo",
	"pycairo",
	"pygobject",
	"source-highlight",
	"devhelp",
}

var GTK2 = []string{
	"gtk+2",
}

var JAVA = []string{
	"openjdk8",
	"gradle",
	"openjfx",
	"icedtea-web",
	"icedtea-sound",
}

var LANGS = []string{
	"go", "php", "ruby", "rustc", "cargo", "fpc",
}

var LIBS = []string{
	"libsodium",
}

var LLVM = []string{
	"cfe", "clang-tools-extra", "compiler-rt", "libcxx", "libcxxabi", "libunwind", "lld", "lldb",
	"llvm", "openmp", "polly", "emscripten",
}

var MEDIA = []string{
	"sane-backends",
	"libsndfile",
	"x264",
	"x265",
	"ffmpeg",
	"mplayer",
	"lame",
	"flac",
	// - cdparanoia-III # project seems abendoned
	"celt",
	"cortado",
	"ezstream",
	"flac",
	"icecast",
	"ices",
	"libao",
	"libfishsound",
	"libogg",
	"liboggz",
	"libshout",
	"libtheora",
	"libvorbis",
	"libquicktime",
	"mgm",
	"opus",
	"opus-tools",
	"opusfile",
	"rogg",
	"speex",
	"speexdsp",
	"vorbis-tools",
	"xvidcore",
	"ghostscript",
	"FreeImage",
	"sox",
	"librsvgmm",
	"librsvg",
	"openjpeg1",
	"openjpeg2",
	"libjpeg-turbo",
	"mjpegtools",
	"jasper",
	"openexr",
	"ilmbase",
	"giflib",
	"giflib4",
	"libungif",
	"openimageio",
	"DevIL",
	"libgd",
	"vigra",
	"djvulibre",
	"tiff",
	"lcms",
	"lcms2",
	"libpng",
	"frei0r-plugins",
	"gimp",
	"gap",
	"gegl",
	"gegl_0_2",
	"gegl_0_3",
	"gsl",
	"babl",
	"gmerlin",
	"gmerlin-avdecoder",
	"gmerlin-effectv",
	"gmerlin-encoders",
	"libmad",
	"madplay",
	"libid3tag",
	"libwebp",
	"libvpx",
	"libexif",
	"exif",
	"a52dec",
	"libgphoto2",
	"gphoto2",
	"popt",
	"libcroco",
	"gst-plugins-base",
	"gst-plugins-good",
	"gst-plugins-bad",
	"gst-plugins-ugly",
	"gst-plugins-gl",
	"gst-ffmpeg",
	"gstreamer",
	"libmusicbrainz",
	"opencv2",
	"opencv3",
	"openal-soft",
	"freealut",
	"audacity",
	"libopenshot",
	"libopenshot-audio",
	"openshot-qt",
}

var NETWORK = []string{
	"monitoring-plugins",
}

var PERLMOD = []string{
	"Net-DNS", "Parallel-ForkManager", "XML-SAX", "NetAddr-IP", "Gtk2-Ex-Utils", "Gtk2", "URI",
	"Mail-SpamAssassin", "Archive-Zip", "XML-NamespaceSupport", "XML-Namespace", "HTML-Parser",
	"XML-SAX-Base", "text-highlight", "XML-Simple", "XML-Parser",
}

var PPP = []string{
	"ppp",
	"rp-pppoe",
	"pptp",
	"pptpd",
}

var QT = []string{
	"qt4", "qt5",
}

var SEC = []string{
	"apparmor", "checkpolicy", "libselinux", "libsemanage", "libsepol", "policycoreutils",
	"sepolgen",
}

var WAYLAND = []string{
	"wayland", "weston", "wayland-protocols",
}

var WEB = []string{
	"nss",
	"nspr",

	// - js185 # deprecated

	"mozjs",
	"mozjs24",
	"mozjs17",

	// NOTE: disabling those: to huge
	// - firefox
	// - thunderbird
	// - seamonkey
	//
	// xulrunner

}

var WX = []string{
	"wxWidgets",
}

var XML = []string{"libxml2", "libxslt"}
